name: Setup
description: Setup Node.js and install dependencies

inputs:
  NPM_TOKEN:
    description: "NPM Token Scoped to @miri-ai"
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - name: Add npmrc
      shell: bash
      run: echo "//registry.npmjs.org/:_authToken=${{ inputs.NPM_TOKEN }}" > ~/.npmrc

    # ExpoExample
    - name: Restore expoexample dependencies
      id: npm-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          **/expoexample/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/expoexample/package-lock.json') }}-${{ hashFiles('**/expoexample/package.json', '!node_modules/**') }}
        restore-keys: |
          ${{ runner.os }}-npm-${{ hashFiles('**/expoexample/package-lock.json') }}
          ${{ runner.os }}-npm-

    - name: Install expoexample dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: cd expoexample && npm install
      shell: bash

    - name: Cache expoexample  dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          **/expoexample/node_modules
        key: ${{ steps.npm-cache.outputs.cache-primary-key }}

    # ReactNativeExample
    - name: Restore reactnativeexample dependencies
      id: npm-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          **/reactnativeexample/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('**/reactnativeexample/package-lock.json') }}-${{ hashFiles('**/reactnativeexample/package.json', '!node_modules/**') }}
        restore-keys: |
          ${{ runner.os }}-npm-${{ hashFiles('**/reactnativeexample/package-lock.json') }}
          ${{ runner.os }}-npm-

    - name: Install reactnativeexample dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: cd reactnativeexample && npm install
      shell: bash

    - name: Cache reactnativeexample  dependencies
      if: steps.npm-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          **/reactnativeexample/node_modules
        key: ${{ steps.npm-cache.outputs.cache-primary-key }}
