name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Lint expoexample files
        run: cd expoexample && npm run lint

      - name: Run expo-doctor
        run: cd expoexample && npx expo-doctor

      - name: Lint reactnativeexample files
        run: cd reactnativeexample && npm run lint

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Prettier check expoexample files
        run: cd expoexample && npm run prettier:check

      - name: Prettier check reactnativeexample files
        run: cd reactnativeexample && npm run prettier:check

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Typecheck expoexample files
        run: cd expoexample && npm run typecheck

      - name: Typecheck reactnativeexample files
        run: cd reactnativeexample && npm run typecheck

  # configuration for this github action is taken from here:
  # https://github.com/marketplace/actions/aqua-security-trivy#scan-ci-pipeline-w-trivy-config
  trivy-scan:
    name: trivy-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          scan-ref: ./
          exit-code: 1
          format: json
          skip-dirs: ./examples
