name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Lint expoexample files
        run: cd expoexample && npm run lint

      - name: Prettier check expoexample files
        run: cd expoexample && npm run prettier:check

      - name: Typecheck expoexample files
        run: cd expoexample && npm run typecheck
